package com.clock.dao;

import com.clock.dao.dataobject.InfoDataObj;

import java.util.List;

public interface InfoDataObjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Oct 18 19:49:01 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Oct 18 19:49:01 CST 2020
     */
    int insert(InfoDataObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Oct 18 19:49:01 CST 2020
     */
    int insertSelective(InfoDataObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Oct 18 19:49:01 CST 2020
     */
    InfoDataObj selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Oct 18 19:49:01 CST 2020
     */
    int updateByPrimaryKeySelective(InfoDataObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Oct 18 19:49:01 CST 2020
     */
    int updateByPrimaryKey(InfoDataObj record);

    List<InfoDataObj> getAllUser();
    InfoDataObj selectByUserName(String username);
}