package com.clock.dao;

import com.clock.dao.dataobject.PasswordDataObj;

public interface PasswordDataObjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Oct 18 19:49:01 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Oct 18 19:49:01 CST 2020
     */
    int insert(PasswordDataObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Oct 18 19:49:01 CST 2020
     */
    int insertSelective(PasswordDataObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Oct 18 19:49:01 CST 2020
     */
    PasswordDataObj selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Oct 18 19:49:01 CST 2020
     */
    int updateByPrimaryKeySelective(PasswordDataObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Oct 18 19:49:01 CST 2020
     */
    int updateByPrimaryKey(PasswordDataObj record);

    PasswordDataObj selectByUserId(Integer userId);

}