package com.clock.dao.dataobject;

import java.util.Date;

public class InfoDataObj {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbg.generated Sun Oct 18 19:49:01 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbg.generated Sun Oct 18 19:49:01 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.getup_date
     *
     * @mbg.generated Sun Oct 18 19:49:01 CST 2020
     */
    private Date getupDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbg.generated Sun Oct 18 19:49:01 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbg.generated Sun Oct 18 19:49:01 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbg.generated Sun Oct 18 19:49:01 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbg.generated Sun Oct 18 19:49:01 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.getup_date
     *
     * @return the value of user_info.getup_date
     *
     * @mbg.generated Sun Oct 18 19:49:01 CST 2020
     */
    public Date getGetupDate() {
        return getupDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.getup_date
     *
     * @param getupDate the value for user_info.getup_date
     *
     * @mbg.generated Sun Oct 18 19:49:01 CST 2020
     */
    public void setGetupDate(Date getupDate) {
        this.getupDate = getupDate;
    }
}